# Generated by Django 3.0.5 on 2021-12-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfaction',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
