# Generated by Django 3.0.5 on 2021-12-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction', '0002_satisfaction_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='satisfaction',
            old_name='user',
            new_name='user_id',
        ),
    ]
